version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: c2s_feedback_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      timeout: 5s

  pgadmin:
    image: dpage/pgadmin4
    container_name: c2s_feedback_pgadmin
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres

  redis:
    image: redis:7
    container_name: c2s_feedback_redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      timeout: 3s

  sidekiq:
    build: .
    container_name: c2s_feedback_sidekiq
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    command: bundle exec sidekiq
    restart: always
    env_file:
      - .env
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://c2s_feedback_redis:6379/0
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/c2s_feedback_development" # Confirme que esta URL está correta
    volumes:
      - .:/app
    working_dir: /app


  web:
    build: .
    container_name: c2s_feedback_web
    restart: always
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    env_file:
      - .env
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://c2s_feedback_redis:6379/0
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/c2s_feedback_development"
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  redis_data:
