---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/health":
    get:
      summary: Retrieves system health
      tags:
      - Health
      responses:
        '200':
          description: health check
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  version:
                    type: string
                  database:
                    type: object
                    properties:
                      connected:
                        type: boolean
                      pool_size:
                        type: integer
                  redis:
                    type: object
                    properties:
                      connected:
                        type: boolean
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
