default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'postgres' %>
  host: <%= ENV['POSTGRES_HOST'] || 'postgres' %>
  port: 5432
  pool: 5

development:
  <<: *default
  database: c2s_feedback_development

test:
  <<: *default
  database: c2s_feedback_test

production:
  <<: *default
  database: c2s_feedback_production
  username: <%= ENV['PROD_POSTGRES_USER'] || 'postgres'%>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'postgres' %>
  host: <%= ENV['PROD_POSTGRES_HOST'] || 'localhost' %>
  port: <%= ENV['PROD_POSTGRES_PORT'] || '5432' %>
