:concurrency: 5
:queues:
  - default
  - mailers
  - low
  - high

:redis:
  url: <%= ENV["REDIS_URL"] %>

:schedule:
  daily_evaluation_summary:
    cron: "59 23 * * *"
    class: "DailyEvaluationSummaryJob"
    queue: "low"